<template>
  <of-field-outer v-bind="fieldAttrs">
    <textarea
      ref="elt"
      v-bind="attrs"
      v-on="handlers"
      :value="inputValue"
    ></textarea>
  </of-field-outer>
</template>

<script lang="ts">
import { ref, defineComponent, SetupContext, computed, Ref, watch } from 'vue'
import OfFieldOuter from './FieldOuter.vue'

const copyAttrs = new Set([
  'autocomplete',
  'placeholder',
  'cols',
  'rows',
  'tabIndex',
  'value'
])

const calcHeight = (input: Ref<HTMLTextAreaElement>) => {
  let ht = input.value && input.value.scrollHeight
  console.log('height', ht)
}

export default defineComponent({
  name: 'of-textarea',
  components: { OfFieldOuter },
  inheritAttrs: false,
  props: {
    class: String,
    config: Object,
    disabled: [Boolean, String],
    id: String,
    modelValue: String,
    placeholder: String,
    readonly: [Boolean, String],
    rows: [Number, String],
    value: String,
    variant: String
  },
  setup(props, ctx: SetupContext) {
    const config = props.config || props
    const elt = ref<HTMLInputElement | undefined>()
    const disabled = computed(() => config.disabled)
    const focused = ref(false)
    const inputValue = ref(
      props.value === undefined ? props.modelValue : props.value
    )
    watch(
      () => props.modelValue,
      val => {
        inputValue.value = val
      }
    )
    const readonly = computed(() => config.readonly && !disabled.value)
    const id = config.id || 'input-' + Math.round(Math.random() * 1000) // FIXME
    const value: Ref<any> = computed({
      get: () => {
        // FIXME format stored value
        // computed() can be generated by the formatter
        inputValue.value
      },
      set: (val: any) => {
        // FIXME unformat value
        inputValue.value = val
      }
    })
    const handlers = {
      blur: (evt: FocusEvent) => {
        focused.value = false
        ctx.emit('blur')
      },
      change: (evt: Event) => {
        inputValue.value = elt.value?.value
        ctx.emit('change', inputValue.value)
      },
      input: (evt: InputEvent) => {
        inputValue.value = elt.value?.value
        ctx.emit('input', inputValue.value)
        ctx.emit('update:modelValue', inputValue.value)
      },
      focus: (evt: FocusEvent) => {
        focused.value = true
        ctx.emit('focus')
      }
    }
    const blank = computed(() => {
      const val = inputValue.value
      return val === undefined || val === null || val === ''
    })
    const fieldAttrs = computed(() => ({
      blank: blank.value,
      class: ['of-field-textarea', config.class],
      config,
      disabled: disabled.value,
      focused: focused.value,
      inputId: id,
      label: config.label,
      readonly: readonly.value,
      variant: config.variant
    }))
    return {
      attrs: computed(() => ({
        id,
        class: 'of-field-input',
        disabled: disabled.value,
        placeholder: config.placeholder,
        readonly: readonly.value,
        rows: config.rows
      })),
      elt,
      fieldAttrs,
      handlers,
      inputValue
    }
  }
})
</script>
