<template>
  <of-field-outer v-bind="fieldAttrs">
    <input ref="elt" v-bind="attrs" v-on="handlers" />
  </of-field-outer>
</template>

<script lang="ts">
import { ref, defineComponent, SetupContext, computed, Ref, watch } from 'vue'
import OfFieldOuter from './FieldOuter.vue'

const copyAttrs = new Set(['autocomplete', 'placeholder', 'size', 'value'])

// types that can be inherited from state.type
// setting state.inputType allows any value
const allowInputTypes = new Set([
  'date',
  'datetime-local',
  'email',
  'month',
  'number',
  'password',
  'tel',
  'time',
  'week',
  'url'
])

const inputTypeFrom = (type?: string) => {
  if (type && allowInputTypes.has(type)) return type
  return 'text'
}

export default defineComponent({
  name: 'of-text-field',
  components: { OfFieldOuter },
  inheritAttrs: false,
  props: {
    class: String,
    config: Object,
    disabled: [Boolean, String],
    id: String,
    label: String,
    maxlength: Number,
    modelValue: String,
    placeholder: String,
    readonly: [Boolean, String],
    value: String,
    variant: String
  },
  setup(props, ctx: SetupContext) {
    const config = props.config || props
    const inputValue = ref(
      props.value === undefined ? props.modelValue : props.value
    )
    watch(
      () => props.modelValue,
      val => {
        inputValue.value = val
      }
    )
    const elt = ref<HTMLInputElement | undefined>()
    const disabled = computed(() => config.disabled)
    const focused = ref(false)
    const readonly = computed(() => config.readonly && !disabled.value)
    const id = config.id || 'input-' + Math.round(Math.random() * 1000) // FIXME
    const value: Ref<any> = computed({
      get: () => {
        // FIXME format stored value
        // computed() can be generated by the formatter
        inputValue.value
      },
      set: (val: any) => {
        // FIXME unformat value
        inputValue.value = val
      }
    })
    const handlers = {
      blur(evt: FocusEvent) {
        focused.value = false
        ctx.emit('blur')
      },
      change(evt: Event) {
        inputValue.value = elt.value?.value
        ctx.emit('change', inputValue.value)
      },
      focus(evt: FocusEvent) {
        focused.value = true
        ctx.emit('focus')
      },
      input(evt: InputEvent) {
        inputValue.value = elt.value?.value
        ctx.emit('input', inputValue.value)
        ctx.emit('update:modelValue', inputValue.value)
      },
      keydown(evt: KeyboardEvent) {
        ctx.emit('keydown', evt)
      }
    }
    const blank = computed(() => {
      // FIXME ask formatter
      const val = inputValue.value
      return val === undefined || val === null || val === ''
    })
    const fieldAttrs = computed(() => ({
      blank: blank.value,
      class: ['of-field-text', config.class],
      disabled: disabled.value,
      focused: focused.value,
      inputId: id,
      label: config.label,
      readonly: readonly.value,
      variant: config.variant
    }))
    return {
      attrs: computed(() => ({
        id,
        class: 'of-field-input',
        disabled: disabled.value,
        maxlength: config.maxlength,
        placeholder: config.placeholder,
        readonly: readonly.value,
        value: inputValue.value
      })),
      elt,
      fieldAttrs,
      handlers
    }
  }
})
</script>
