<template>
  <of-field-outer v-bind="fieldAttrs">
    <input ref="elt" v-bind="attrs" v-on="handlers" />
  </of-field-outer>
</template>

<script lang="ts">
import { ref, defineComponent, SetupContext, computed, Ref, watch } from 'vue'
import OfFieldOuter from './FieldOuter.vue'
import { NumberFormatter } from '../lib/format'

// const copyAttrs = new Set(['autocomplete', 'placeholder', 'size', 'value'])

// types that can be inherited from state.type
// setting state.inputType allows any value
const allowInputTypes = new Set([
  'date',
  'datetime-local',
  'email',
  'month',
  'number',
  'password',
  'tel',
  'time',
  'week',
  'url'
])

const inputTypeFrom = (type?: string) => {
  if (type && allowInputTypes.has(type)) return type
  return 'text'
}

export default defineComponent({
  name: 'of-text-field',
  components: { OfFieldOuter },
  inheritAttrs: false,
  props: {
    class: String,
    disabled: Boolean,
    format: [String, Object],
    id: String,
    label: String,
    maxlength: Number,
    modelValue: [String, Number, Date],
    name: String,
    placeholder: String,
    readonly: Boolean,
    value: String,
    variant: String
  },
  setup(props, ctx: SetupContext) {
    // FIXME - get formatter instance from config as a computed ref
    const formatter = props.format === 'number' ? new NumberFormatter() : null
    let initValue = props.value === undefined ? props.modelValue : props.value
    if (formatter) {
      initValue = formatter.format(initValue)
    }
    const inputValue = ref(initValue)
    watch(
      () => props.modelValue,
      val => {
        inputValue.value = val
      }
    )
    const elt = ref<HTMLInputElement | undefined>()
    const disabled = computed(() => props.disabled)
    const focused = ref(false)
    const readonly = computed(() => props.readonly && !disabled.value)
    const id = props.id || 'input-' + Math.round(Math.random() * 1000) // FIXME
    const value: Ref<any> = computed({
      get: () => {
        // FIXME format stored value
        // computed() can be generated by the formatter
        inputValue.value
      },
      set: (val: any) => {
        // FIXME unformat value
        inputValue.value = val
      }
    })
    const handlers = {
      blur(evt: FocusEvent) {
        focused.value = false
      },
      change(evt: Event) {
        inputValue.value = elt.value?.value
      },
      focus(evt: FocusEvent) {
        focused.value = true
      },
      input(evt: InputEvent) {
        if (formatter) {
          formatter.handleInput(evt)
        }
        // inputValue.value = elt.value?.value // FIXME - makes safari jump to end of input
        // will become update:modelInput with modelValue bound to change event
        ctx.emit('update:modelValue', inputValue.value)
      },
      keydown(evt: KeyboardEvent) {
        if (formatter) {
          formatter.handleKeyDown(evt)
        }
      }
    }
    const blank = computed(() => {
      // FIXME ask formatter
      const val = inputValue.value
      return val === undefined || val === null || val === ''
    })
    const fieldAttrs = computed(() => ({
      blank: blank.value,
      class: ['of-field-text', props.class],
      disabled: disabled.value,
      focused: focused.value,
      inputId: id,
      label: props.label,
      readonly: readonly.value,
      variant: props.variant
    }))
    return {
      attrs: computed(() => ({
        id,
        class: 'of-field-input',
        disabled: disabled.value,
        inputmode: formatter ? formatter.inputMode() : undefined,
        maxlength: props.maxlength,
        name: props.name,
        placeholder: props.placeholder,
        readonly: readonly.value,
        value: inputValue.value
      })),
      elt,
      fieldAttrs,
      handlers
    }
  }
})
</script>
