<template>
  <field-outer v-bind="fieldAttrs">
    <textarea
      ref="elt"
      v-bind="attrs"
      v-on="handlers"
      :value="inputValue"
    ></textarea>
  </field-outer>
</template>

<script lang="ts">
import {
  ref,
  defineComponent,
  SetupContext,
  reactive,
  computed,
  Ref
} from 'vue'
import { FieldConfig, FieldState, fieldState } from '../lib/field'
import { StoreRef, storeRef } from '../lib/store'
import { hasOwn } from '../lib/util'
import FieldOuter from './FieldOuter.vue'

const copyAttrs = new Set([
  'autocomplete',
  'placeholder',
  'cols',
  'rows',
  'tabIndex',
  'value'
])

const mapStateAttrs = {
  id: 'inputId',
  class: 'inputClass',
  maxlength: 'maxLength',
  readonly: 'readOnly',
  required: 'required',
  style: 'inputStyle',
  tabindex: 'tabIndex',
  variant: 'inputVariant'
}

const variantClasses: Record<string, string> = {
  default: 'input-text',
  plain: ''
}

const calcHeight = (input: Ref<HTMLTextAreaElement>) => {
  let ht = input.value && input.value.scrollHeight
  console.log('height', ht)
}

const makeAttrs = (state: FieldState, input: Ref<HTMLTextAreaElement>) => {
  const result: Record<string, any> = Object.assign({}, state.inputAttrs)
  for (const k of copyAttrs) {
    const v = state[k] as any
    if (v !== undefined) result[k] = v
  }
  if (state.disabled) {
    result['disabled'] = true
  } else if (state.readOnly || state.store.locked) {
    result['readOnly'] = true
  }
  result['id'] = state.inputId
  result['class'] = [
    variantClasses[(state.inputVariant || 'default') as string],
    state.inputClass
  ]
  // FIXME make autogrow a property
  result['style'] = [calcHeight(input), state.inputStyle]
  return result
}

const loadContextAttrs = (attrs: Record<string, any>, state: FieldState) => {
  if (!attrs) return
  for (const k in attrs) {
    if (k === 'state' || k === 'value') continue
    if (hasOwn(mapStateAttrs, k)) {
      // FIXME may want to merge values, inputClass/Style can hold a list
      state[mapStateAttrs[k]] = attrs[k]
    } else {
      if (!state.inputAttrs) state.inputAttrs = {}
      state.inputAttrs[k] = attrs[k]
    }
  }
}

export default defineComponent({
  name: 'input-textarea',
  components: { FieldOuter },
  inheritAttrs: false,
  async setup(
    props: {
      class?: string // or object or list
      config?: FieldConfig
      disabled?: boolean
      id?: string
      placeholder?: string
      readonly?: boolean
      store?: StoreRef
      value?: string
      variant?: string
      [key: string]: any
    },
    ctx: SetupContext
  ) {
    // FIXME avoid duplication from input-text
    const config = props.config || {}
    const initValue = props.value === undefined ? config.value : props.value
    const store = props.store || storeRef(initValue)
    const elt = ref<HTMLInputElement>()
    const disabled = computed(() => config.disabled || props.disabled)
    const focused = ref(false)
    const readonly = computed(
      () => (config.readonly || props.readonly) && !disabled.value
    )
    const id =
      props.id || config.id || 'input-' + Math.round(Math.random() * 1000) // FIXME
    const value: Ref<any> = computed({
      get: () => {
        // FIXME format stored value
        // computed() can be generated by the formatter
        store.value
      },
      set: (val: any) => {
        // FIXME unformat value
        store.value = val
      }
    })
    const inputValue = ref(initValue)
    const handlers = {
      blur: (evt: FocusEvent) => {
        focused.value = false
      },
      change: (evt: Event) => {
        inputValue.value = elt.value.value
        store.value = elt.value.value
      },
      input: (evt: InputEvent) => {
        inputValue.value = elt.value.value
      },
      focus: (evt: FocusEvent) => {
        focused.value = true
      }
    }
    const blank = computed(() => {
      const val = inputValue.value
      return val === undefined || val === null || val === ''
    })
    const fieldAttrs = computed(() => ({
      blank: blank.value,
      class: ['field-textarea', props.class],
      config,
      disabled: disabled.value,
      focused: focused.value,
      inputId: id,
      label: config.label,
      readonly: readonly.value,
      store,
      variant: props.variant
    }))
    return {
      attrs: computed(() => ({
        id,
        class: 'field-input',
        disabled: disabled.value,
        placeholder: props.placeholder || config.placeholder,
        readonly: readonly.value
      })),
      elt,
      fieldAttrs,
      handlers,
      inputValue
    }
  }
})
</script>
