<template>
  <div ref="other"></div>
  <field-outer v-bind="fieldAttrs">
    <input ref="elt" v-bind="attrs" v-on="handlers" :value="inputValue" />
  </field-outer>
</template>

<script lang="ts">
import {
  ref,
  defineComponent,
  SetupContext,
  reactive,
  computed,
  Ref
} from 'vue'
import { FieldConfig, FieldState, fieldState } from '../lib/field'
import FieldOuter from './FieldOuter.vue'
import { StoreRef, storeRef } from '../lib/store'
import { hasOwn } from '../lib/util'

const copyAttrs = new Set([
  'autocomplete',
  'placeholder',
  'size',
  'tabIndex',
  'value'
])

const mapStateAttrs = {
  id: 'inputId',
  class: 'inputClass',
  maxlength: 'maxLength',
  readonly: 'readOnly',
  required: 'required',
  style: 'inputStyle',
  tabindex: 'tabIndex',
  type: 'inputType',
  variant: 'inputVariant'
}

// types that can be inherited from state.type
// setting state.inputType allows any value
const allowInputTypes = new Set([
  'date',
  'datetime-local',
  'email',
  'month',
  'number',
  'password',
  'tel',
  'time',
  'week',
  'url'
])

const inputTypeFrom = (type?: string) => {
  if (type && allowInputTypes.has(type)) return type
  return 'text'
}

const variantClasses: Record<string, string> = {
  default: 'input-text',
  plain: ''
}

const makeAttrs = (
  config: FieldConfig,
  id: string,
  attrs: Record<string, any>
) => {
  const result: Record<string, any> = {}
  /*for (const k of copyAttrs) {
    const v = state[k] as any
    if (v !== undefined) result[k] = v
  }
  if (state.disabled) {
    result['disabled'] = true
  } else if (state.readOnly || state.store.locked) {
    result['readOnly'] = true
  }
  result['id'] = state.inputId
  result['class'] = [
    variantClasses[(state.inputVariant || 'default') as string],
    state.inputClass
  ]
  result['style'] = state.inputStyle
  result['type'] = state.inputType || inputTypeFrom(state.type)*/
  result['id'] = id
  result['class'] = 'field-input field-text'
  return result
}

const loadContextAttrs = (attrs: Record<string, any>, state: FieldState) => {
  if (!attrs) return
  const result = {}
  for (const k in attrs) {
    if (k === 'config' || k === 'store' || k === 'value') continue
    if (hasOwn(mapStateAttrs, k)) {
      // FIXME may want to merge values, inputClass/Style can hold a list
      state[mapStateAttrs[k]] = attrs[k]
    } else {
      if (!state.inputAttrs) state.inputAttrs = {}
      state.inputAttrs[k] = attrs[k]
    }
  }
}

export default defineComponent({
  name: 'input-text',
  components: { FieldOuter },
  inheritAttrs: false,
  async setup(
    props: {
      config?: FieldConfig
      id?: string
      store?: StoreRef
      value?: any
      variant?: string
      [key: string]: any
    },
    ctx: SetupContext
  ) {
    const config = props.config || {}
    const elt = ref<HTMLInputElement>()
    const other = ref<HTMLElement>()
    const focused = ref(false)
    const id =
      props.id || config.id || 'input-' + Math.round(Math.random() * 1000) // FIXME
    const initValue = props.value === undefined ? config.value : props.value
    const store = props.store || storeRef(initValue)
    const value: Ref<any> = computed({
      get: () => {
        // FIXME format stored value
        // computed() can be generated by the formatter
        store.value
      },
      set: (val: any) => {
        // FIXME unformat value
        store.value = val
      }
    })
    const inputValue = ref(initValue)
    const handlers = {
      blur: (evt: FocusEvent) => {
        focused.value = false
      },
      change: (evt: Event) => {
        inputValue.value = elt.value.value
        store.value = elt.value.value
      },
      input: (evt: InputEvent) => {
        inputValue.value = elt.value.value
      },
      focus: (evt: FocusEvent) => {
        focused.value = true
      }
    }
    const blank = computed(() => {
      const val = inputValue.value
      console.log(val)
      return val === undefined || val === null || val === ''
    })
    const fieldAttrs = computed(() => ({
      blank: blank.value,
      config,
      focused: focused.value,
      inputId: id,
      store,
      variant: props.variant
    }))
    return {
      attrs: computed(() => ({
        id,
        class: 'field-input field-text'
      })),
      blank,
      elt,
      fieldAttrs,
      focused,
      handlers,
      id,
      inputValue,
      other,
      store,
      value
    }
  }
})
</script>
